"""Shared fixtures: expensive model fits computed once per session.

All data is generated by the seeded synthetic generators -- the suite is
fully offline and deterministic.
"""

from __future__ import annotations

import numpy as np
import pytest

from fx_vol import fit_egarch, fit_garch, fit_gjr
from fx_vol.data import synthetic as syn

# ---- true parameters used across recovery tests -------------------------

GARCH_TRUE = {"omega": 1e-6, "alpha": 0.05, "beta": 0.92}
GARCH_T_TRUE = {"omega": 1.5e-6, "alpha": 0.06, "beta": 0.90, "nu": 6.0}
GJR_TRUE = {"omega": 1e-6, "alpha": 0.03, "gamma": 0.10, "beta": 0.88}
EGARCH_TRUE = {"omega": -0.50, "alpha": 0.15, "gamma": -0.06, "beta": 0.95}
GARCHX_TRUE = {"omega": 1e-6, "alpha": 0.05, "beta": 0.90, "gamma_x": 5e-5, "event_prob": 0.05}


@pytest.fixture(scope="session")
def garch_sim():
    r, sigma2 = syn.simulate_garch(
        20_000, seed=11, return_sigma2=True, **GARCH_TRUE
    )
    return r, sigma2


@pytest.fixture(scope="session")
def garch_fit(garch_sim):
    return fit_garch(garch_sim[0], dist="gaussian")


@pytest.fixture(scope="session")
def garch_t_sim():
    p = GARCH_T_TRUE
    return syn.simulate_garch(
        20_000, omega=p["omega"], alpha=p["alpha"], beta=p["beta"],
        dist="t", nu=p["nu"], seed=12,
    )


@pytest.fixture(scope="session")
def garch_t_fit(garch_t_sim):
    return fit_garch(garch_t_sim, dist="t")


@pytest.fixture(scope="session")
def gjr_sim():
    return syn.simulate_gjr(20_000, seed=13, **GJR_TRUE)


@pytest.fixture(scope="session")
def gjr_fit(gjr_sim):
    return fit_gjr(gjr_sim, dist="gaussian")


@pytest.fixture(scope="session")
def egarch_sim():
    return syn.simulate_egarch(15_000, seed=14, **EGARCH_TRUE)


@pytest.fixture(scope="session")
def egarch_fit(egarch_sim):
    return fit_egarch(egarch_sim, dist="gaussian")


@pytest.fixture(scope="session")
def garchx_sim():
    p = GARCHX_TRUE
    r, x = syn.simulate_garch_x(
        20_000, omega=p["omega"], alpha=p["alpha"], beta=p["beta"],
        gamma_x=p["gamma_x"], event_prob=p["event_prob"], seed=15,
    )
    return r, x


@pytest.fixture(scope="session")
def garchx_fit(garchx_sim):
    r, x = garchx_sim
    return fit_garch(r, dist="gaussian", x=x)


@pytest.fixture(scope="session")
def symmetric_garch_fit_on_gjr(gjr_sim):
    """Symmetric GARCH deliberately (mis)fitted to asymmetric GJR data."""
    return fit_garch(gjr_sim, dist="gaussian")
