//! Cross-language golden validation: every case generated by the Python
//! reference implementation must reproduce to better than 1e-9 (source
//! vectors carry 1e-10 self-consistency; unit conventions identical).

mod common;
use common::assert_close;

use fx_options_engine::golden::CASES;
use fx_options_engine::{analytic_greeks, delta, gk_price, DeltaConvention};

const TOL: f64 = 1e-9;

#[test]
fn golden_has_thirty_cases() {
    assert_eq!(CASES.len(), 30);
}

#[test]
fn golden_prices_match_python() {
    for (i, c) in CASES.iter().enumerate() {
        let px = gk_price(c.s, c.k, c.t, c.r_d, c.r_f, c.sigma, c.option_type).unwrap();
        assert_close(px, c.price, TOL, &format!("case {i} price"));
    }
}

#[test]
fn golden_deltas_match_python() {
    for (i, c) in CASES.iter().enumerate() {
        let ds = delta(
            c.s,
            c.k,
            c.t,
            c.r_d,
            c.r_f,
            c.sigma,
            c.option_type,
            DeltaConvention::Spot,
        )
        .unwrap();
        let df = delta(
            c.s,
            c.k,
            c.t,
            c.r_d,
            c.r_f,
            c.sigma,
            c.option_type,
            DeltaConvention::Forward,
        )
        .unwrap();
        assert_close(ds, c.delta_spot, TOL, &format!("case {i} delta_spot"));
        assert_close(df, c.delta_fwd, TOL, &format!("case {i} delta_fwd"));
    }
}

#[test]
fn golden_greeks_match_python() {
    for (i, c) in CASES.iter().enumerate() {
        let g = analytic_greeks(c.s, c.k, c.t, c.r_d, c.r_f, c.sigma, c.option_type).unwrap();
        assert_close(g.price, c.price, TOL, &format!("case {i} greeks.price"));
        assert_close(
            g.delta_spot,
            c.delta_spot,
            TOL,
            &format!("case {i} greeks.delta_spot"),
        );
        assert_close(
            g.delta_forward,
            c.delta_fwd,
            TOL,
            &format!("case {i} greeks.delta_forward"),
        );
        assert_close(g.gamma, c.gamma, TOL, &format!("case {i} gamma"));
        assert_close(g.vega, c.vega, TOL, &format!("case {i} vega"));
        assert_close(g.theta, c.theta, TOL, &format!("case {i} theta"));
        assert_close(g.rho_domestic, c.rho_d, TOL, &format!("case {i} rho_d"));
        assert_close(g.rho_foreign, c.rho_f, TOL, &format!("case {i} rho_f"));
    }
}
