#!/usr/bin/env python3
"""Generate src/golden.rs from the Python reference golden JSON.

Reads the golden vectors produced by the Python project
(python/equity/01-options-pricing/tests/golden/golden_vectors.json) and
emits a `pub const` array of structs for the Rust integration tests.

Doubles are emitted via Python's shortest-roundtrip ``repr``, which parses
back to the bit-identical IEEE-754 double in Rust, so the committed module
carries the Python reference values exactly.

Usage:
    python3 tools/gen_golden_rs.py [json_path] [rs_path]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_JSON = (
    HERE.parents[2]
    / "python/equity/01-options-pricing/tests/golden/golden_vectors.json"
)
DEFAULT_RS = HERE.parent / "src/golden.rs"


def fmt(x: float) -> str:
    """Shortest decimal that round-trips to the same IEEE-754 double."""
    s = repr(float(x))
    # Rust f64 literals need a '.' or exponent marker.
    return s if any(c in s for c in ".eE") else s + ".0"


def main() -> int:
    json_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_JSON
    rs_path = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_RS

    data = json.loads(json_path.read_text())
    cases = data["cases"]
    if len(cases) != data["n_cases"]:
        raise SystemExit(f"n_cases={data['n_cases']} but found {len(cases)} cases")

    lines: list[str] = []
    lines.append("//! GENERATED by tools/gen_golden_rs.py — do not edit.")
    lines.append("//!")
    lines.append("//! Source: python/equity/01-options-pricing/tests/golden/")
    lines.append("//! golden_vectors.json")
    lines.append("//!")
    for chunk in _wrap(data["description"]):
        lines.append(f"//! {chunk}")
    lines.append("")
    lines.append("use crate::black_scholes::OptionType;")
    lines.append("")
    lines.append("/// One cross-language golden case: inputs plus the Python reference")
    lines.append("/// outputs (theta per year, vega per unit vol, rho per unit rate).")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub struct GoldenCase {")
    for field, doc in (
        ("s", "Spot price."),
        ("k", "Strike price."),
        ("t", "Time to expiry, years (ACT/365F)."),
        ("r", "Continuously compounded annualised risk-free rate."),
        ("q", "Continuously compounded annualised dividend yield."),
        ("sigma", "Annualised log-return volatility."),
    ):
        lines.append(f"    /// {doc}")
        lines.append(f"    pub {field}: f64,")
    lines.append("    /// Option payoff direction.")
    lines.append("    pub option_type: OptionType,")
    for field, doc in (
        ("price", "Reference present value."),
        ("delta", "Reference dV/dS."),
        ("gamma", "Reference d2V/dS2."),
        ("vega", "Reference dV/dsigma (per unit vol)."),
        ("theta", "Reference dV/dt (per year)."),
        ("rho", "Reference dV/dr (per unit rate)."),
    ):
        lines.append(f"    /// {doc}")
        lines.append(f"    pub {field}: f64,")
    lines.append("}")
    lines.append("")
    lines.append(f"/// The {len(cases)} golden cases from the Python reference project.")
    lines.append(f"pub const CASES: [GoldenCase; {len(cases)}] = [")
    for c in cases:
        i, o = c["inputs"], c["outputs"]
        ot = "OptionType::Call" if i["type"] == "call" else "OptionType::Put"
        lines.append("    GoldenCase {")
        lines.append(
            f"        s: {fmt(i['S'])}, k: {fmt(i['K'])}, t: {fmt(i['T'])},"
        )
        lines.append(
            f"        r: {fmt(i['r'])}, q: {fmt(i['q'])}, sigma: {fmt(i['sigma'])},"
        )
        lines.append(f"        option_type: {ot},")
        lines.append(
            f"        price: {fmt(o['price'])}, delta: {fmt(o['delta'])},"
        )
        lines.append(
            f"        gamma: {fmt(o['gamma'])}, vega: {fmt(o['vega'])},"
        )
        lines.append(
            f"        theta: {fmt(o['theta'])}, rho: {fmt(o['rho'])},"
        )
        lines.append("    },")
    lines.append("];")
    lines.append("")

    rs_path.write_text("\n".join(lines))
    print(f"wrote {rs_path} ({len(cases)} cases)")
    return 0


def _wrap(text: str, width: int = 72) -> list[str]:
    words = text.split()
    out: list[str] = []
    cur = ""
    for w in words:
        if len(cur) + len(w) + 1 > width and cur:
            out.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        out.append(cur)
    return out


if __name__ == "__main__":
    raise SystemExit(main())
