//! GENERATED by tools/gen_golden_rs.py — do not edit.
//!
//! Source: python/equity/01-options-pricing/tests/golden/
//! golden_vectors.json
//!
//! Golden Black-Scholes-Merton vectors for cross-validating the C++/Rust
//! engines against the eq_options Python reference. Conventions:
//! continuously compounded annualised r/q (ACT/365F), T in years, sigma
//! annualised; theta per year; vega per unit vol; rho per unit rate.
//! Tolerance for consumers: 1e-10 absolute.

use crate::black_scholes::OptionType;

/// One cross-language golden case: inputs plus the Python reference
/// outputs (theta per year, vega per unit vol, rho per unit rate).
#[derive(Debug, Clone, Copy)]
pub struct GoldenCase {
    /// Spot price.
    pub s: f64,
    /// Strike price.
    pub k: f64,
    /// Time to expiry, years (ACT/365F).
    pub t: f64,
    /// Continuously compounded annualised risk-free rate.
    pub r: f64,
    /// Continuously compounded annualised dividend yield.
    pub q: f64,
    /// Annualised log-return volatility.
    pub sigma: f64,
    /// Option payoff direction.
    pub option_type: OptionType,
    /// Reference present value.
    pub price: f64,
    /// Reference dV/dS.
    pub delta: f64,
    /// Reference d2V/dS2.
    pub gamma: f64,
    /// Reference dV/dsigma (per unit vol).
    pub vega: f64,
    /// Reference dV/dt (per year).
    pub theta: f64,
    /// Reference dV/dr (per unit rate).
    pub rho: f64,
}

/// The 32 golden cases from the Python reference project.
pub const CASES: [GoldenCase; 32] = [
    GoldenCase {
        s: 100.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 0.2,
        option_type: OptionType::Call,
        price: 10.450583572185565, delta: 0.6368306511756191,
        gamma: 0.018762017345846895, vega: 37.52403469169379,
        theta: -6.414027546438197, rho: 53.232481545376345,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 0.2,
        option_type: OptionType::Put,
        price: 5.573526022256971, delta: -0.3631693488243809,
        gamma: 0.018762017345846895, vega: 37.52403469169379,
        theta: -1.657880423934626, rho: -41.89046090469506,
    },
    GoldenCase {
        s: 42.0, k: 40.0, t: 0.5,
        r: 0.1, q: 0.0, sigma: 0.2,
        option_type: OptionType::Call,
        price: 4.759422392871532, delta: 0.779131290942669,
        gamma: 0.04996267040591185, vega: 8.813415059602853,
        theta: -4.559092194592627, rho: 13.982045913360283,
    },
    GoldenCase {
        s: 42.0, k: 40.0, t: 0.5,
        r: 0.1, q: 0.0, sigma: 0.2,
        option_type: OptionType::Put,
        price: 0.8085993729000922, delta: -0.22086870905733103,
        gamma: 0.04996267040591185, vega: 8.813415059602853,
        theta: -0.7541744965897708, rho: -5.0425425766539975,
    },
    GoldenCase {
        s: 100.0, k: 110.0, t: 0.25,
        r: 0.03, q: 0.01, sigma: 0.3,
        option_type: OptionType::Call,
        price: 2.6274945452310376, delta: 0.29832648134663675,
        gamma: 0.023089230052776934, vega: 17.316922539582702,
        theta: -10.907981650085963, rho: 6.801288397358159,
    },
    GoldenCase {
        s: 100.0, k: 110.0, t: 0.25,
        r: 0.03, q: 0.01, sigma: 0.3,
        option_type: OptionType::Put,
        price: 12.055268335590256, delta: -0.6991766410508233,
        gamma: 0.023089230052776934, vega: 17.316922539582702,
        theta: -8.630142191580266, rho: -20.49323311016815,
    },
    GoldenCase {
        s: 100.0, k: 90.0, t: 2.0,
        r: 0.02, q: 0.03, sigma: 0.15,
        option_type: OptionType::Call,
        price: 12.089105767265302, delta: 0.6539936690355497,
        gamma: 0.015563485548540425, vega: 46.690456645621275,
        theta: -0.8551163398299417, rho: 106.62052227257932,
    },
    GoldenCase {
        s: 100.0, k: 90.0, t: 2.0,
        r: 0.02, q: 0.03, sigma: 0.15,
        option_type: OptionType::Put,
        price: 4.383701932549521, delta: -0.28777086454869905,
        gamma: 0.015563485548540425, vega: 46.690456645621275,
        theta: -1.9509889501085063, rho: -66.32157677483885,
    },
    GoldenCase {
        s: 50.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 0.4,
        option_type: OptionType::Call,
        price: 0.6201277299544579, delta: 0.07958508728744629,
        gamma: 0.007404133223020154, vega: 7.404133223020154,
        theta: -1.6487829763249238, rho: 3.3591266344178567,
    },
    GoldenCase {
        s: 50.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 0.4,
        option_type: OptionType::Put,
        price: 45.74307018002586, delta: -0.9204149127125537,
        gamma: 0.007404133223020154, vega: 7.404133223020154,
        theta: 3.1073641461786465, rho: -91.76381581565354,
    },
    GoldenCase {
        s: 200.0, k: 100.0, t: 0.5,
        r: 0.04, q: 0.02, sigma: 0.25,
        option_type: OptionType::Call,
        price: 99.99029302530148, delta: 0.9900261571545957,
        gamma: 2.8719391075683444e-06, vega: 0.014359695537841723,
        theta: 0.03591716850921589, rho: 49.00746920280883,
    },
    GoldenCase {
        s: 200.0, k: 100.0, t: 0.5,
        r: 0.04, q: 0.02, sigma: 0.25,
        option_type: OptionType::Put,
        price: 0.00019360614338855865, delta: -2.3676594572345553e-05,
        gamma: 2.8719391075683444e-06, vega: 0.014359695537841723,
        theta: -0.0034874732604355057, rho: -0.0024644625289288345,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 0.02,
        r: 0.02, q: 0.0, sigma: 0.2,
        option_type: OptionType::Call,
        price: 1.148224735125524, delta: 0.5112822873459225,
        gamma: 0.14099098821087164, vega: 5.6396395284348655,
        theta: -29.197797722163664, rho: 0.9996000799893344,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 0.02,
        r: 0.02, q: 0.0, sigma: 0.2,
        option_type: OptionType::Put,
        price: 1.1082327340589728, delta: -0.48871771265407754,
        gamma: 0.14099098821087164, vega: 5.6396395284348655,
        theta: -27.198597562184993, rho: -0.9996000799893344,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 5.0,
        r: 0.03, q: 0.02, sigma: 0.22,
        option_type: OptionType::Call,
        price: 19.44481516886959, delta: 0.5754153402361734,
        gamma: 0.006907722902615107, vega: 75.98495192876618,
        theta: -1.6637398276029414, rho: 190.4835942737387,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 5.0,
        r: 0.03, q: 0.02, sigma: 0.22,
        option_type: OptionType::Put,
        price: 15.031871007779422, delta: -0.32942207779978616,
        gamma: 0.006907722902615107, vega: 75.98495192876618,
        theta: -0.8912907343996872, rho: -239.8703939387902,
    },
    GoldenCase {
        s: 100.0, k: 105.0, t: 1.0,
        r: -0.01, q: 0.0, sigma: 0.2,
        option_type: OptionType::Call,
        price: 5.5298327649292744, delta: 0.42310719493649335,
        gamma: 0.019575445725729293, vega: 39.150891451458584,
        theta: -3.5472802778586576, rho: 36.78088672872006,
    },
    GoldenCase {
        s: 100.0, k: 105.0, t: 1.0,
        r: -0.01, q: 0.0, sigma: 0.2,
        option_type: OptionType::Put,
        price: 11.585100308766897, delta: -0.5768928050635067,
        gamma: 0.019575445725729293, vega: 39.150891451458584,
        theta: -4.607832953297034, rho: -69.27438081511757,
    },
    GoldenCase {
        s: 100.0, k: 95.0, t: 0.75,
        r: 0.02, q: 0.05, sigma: 0.18,
        option_type: OptionType::Call,
        price: 7.366061742626677, delta: 0.581374849471966,
        gamma: 0.02381446470343069, vega: 32.149527349631434,
        theta: -1.9664974986873403, rho: 38.07856740342745,
    },
    GoldenCase {
        s: 100.0, k: 95.0, t: 0.75,
        r: 0.02, q: 0.05, sigma: 0.18,
        option_type: OptionType::Put,
        price: 4.632254232835443, delta: -0.3818195682488557,
        gamma: 0.02381446470343069, vega: 32.149527349631434,
        theta: -4.91075690204563, rho: -32.11065829329076,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 0.01,
        option_type: OptionType::Call,
        price: 4.877057602069669, delta: 0.9999997206898449,
        gamma: 1.4499941540861075e-06, vega: 0.00014499941540861076,
        theta: -4.756146448342818, rho: 95.12291446691482,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 0.01,
        option_type: OptionType::Put,
        price: 5.2141072075884636e-08, delta: -2.793101551558238e-07,
        gamma: 1.4499941540861075e-06, vega: 0.00014499941540861076,
        theta: 6.741607523398593e-07, rho: -2.7983156587658265e-05,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 1.5,
        option_type: OptionType::Call,
        price: 55.804278366854064, delta: 0.7832843031498372,
        gamma: 0.0019569279988163766, vega: 29.353919982245646,
        theta: -23.14164758409072, rho: 22.524151948129656,
    },
    GoldenCase {
        s: 100.0, k: 100.0, t: 1.0,
        r: 0.05, q: 0.0, sigma: 1.5,
        option_type: OptionType::Put,
        price: 50.92722081692547, delta: -0.2167156968501628,
        gamma: 0.0019569279988163766, vega: 29.353919982245646,
        theta: -18.38550046158715, rho: -72.59879050194175,
    },
    GoldenCase {
        s: 5.0, k: 5.0, t: 0.3,
        r: 0.06, q: 0.0, sigma: 0.45,
        option_type: OptionType::Call,
        price: 0.5319173193101925, delta: 0.5777995031338667,
        gamma: 0.3175427690904528, vega: 1.071706845680278,
        theta: -0.9452049460417573, rho: 0.7071240589077424,
    },
    GoldenCase {
        s: 5.0, k: 7.5, t: 0.3,
        r: 0.06, q: 0.0, sigma: 0.45,
        option_type: OptionType::Put,
        price: 2.4031264215642674, delta: -0.9263015267607143,
        gamma: 0.11333866565621097, vega: 0.382517996589712,
        theta: 0.13518954587978627, rho: -2.1103902166103516,
    },
    GoldenCase {
        s: 1000.0, k: 1200.0, t: 1.5,
        r: 0.045, q: 0.015, sigma: 0.28,
        option_type: OptionType::Call,
        price: 82.12295938563375, delta: 0.40033511359764207,
        gamma: 0.0011080261116680357, vega: 465.37096690057484,
        theta: -51.749143812962735, rho: 477.31823131801247,
    },
    GoldenCase {
        s: 1000.0, k: 800.0, t: 1.5,
        r: 0.045, q: 0.015, sigma: 0.28,
        option_type: OptionType::Put,
        price: 36.0734331284153, delta: -0.1664104001697973,
        gamma: 0.0007220372380826116, vega: 303.2556399946968,
        theta: -21.688243236965768, rho: -303.7257499473189,
    },
    GoldenCase {
        s: 75.0, k: 70.0, t: 0.5,
        r: 0.1, q: 0.05, sigma: 0.35,
        option_type: OptionType::Call,
        price: 10.649137515710322, delta: 0.6756019944667413,
        gamma: 0.018466383826289845, vega: 18.17784657900407,
        theta: -7.83084003033067, rho: 20.010506034647637,
    },
    GoldenCase {
        s: 75.0, k: 70.0, t: 0.5,
        r: 0.1, q: 0.05, sigma: 0.35,
        option_type: OptionType::Put,
        price: 4.086953828635355, delta: -0.2997079175615913,
        gamma: 0.018466383826289845, vega: 18.17784657900407,
        theta: -4.829646228931919, rho: -13.282523822877351,
    },
    GoldenCase {
        s: 100.0, k: 60.0, t: 0.1,
        r: 0.0, q: 0.0, sigma: 0.5,
        option_type: OptionType::Call,
        price: 40.00201787347662, delta: 0.9995331898184572,
        gamma: 0.00010547219841203127, vega: 0.05273609920601563,
        theta: -0.13184024801503907, rho: 5.99513011083691,
    },
    GoldenCase {
        s: 100.0, k: 160.0, t: 0.1,
        r: 0.0, q: 0.0, sigma: 0.5,
        option_type: OptionType::Put,
        price: 60.00839539642156, delta: -0.9980951710806557,
        gamma: 0.0003836191065786583, vega: 0.19180955328932914,
        theta: -0.47952388322332284, rho: -15.981791250448715,
    },
];
