#!/usr/bin/env python3
"""Generate tests/golden_vectors.hpp from the Python reference golden JSON.

Reads the golden vectors produced by the Python project
(python/equity/01-options-pricing/tests/golden/golden_vectors.json) and
emits a constexpr array of structs for the C++ GoogleTest suite.

Doubles are emitted via Python's shortest-roundtrip ``repr``, which parses
back to the bit-identical IEEE-754 double in C++, so the committed header
carries the Python reference values exactly.

Usage:
    python3 tools/gen_golden_header.py [json_path] [header_path]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_JSON = (
    HERE.parents[2]
    / "python/equity/01-options-pricing/tests/golden/golden_vectors.json"
)
DEFAULT_HEADER = HERE.parent / "tests/golden_vectors.hpp"


def fmt(x: float) -> str:
    """Shortest decimal that round-trips to the same IEEE-754 double."""
    s = repr(float(x))
    # Ensure the literal is a double literal in C++ (repr of ints in float
    # form already contains '.', 'e' or 'inf'/'nan' never appear here).
    return s if any(c in s for c in ".eE") else s + ".0"


def main() -> int:
    json_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_JSON
    header_path = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_HEADER

    data = json.loads(json_path.read_text())
    cases = data["cases"]
    if len(cases) != data["n_cases"]:
        raise SystemExit(
            f"n_cases={data['n_cases']} but found {len(cases)} cases"
        )

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen_golden_header.py — do not edit.")
    lines.append("// Source: python/equity/01-options-pricing/tests/golden/"
                 "golden_vectors.json")
    lines.append(f"// {data['description']}")
    lines.append("")
    lines.append("#ifndef EQOPT_TESTS_GOLDEN_VECTORS_HPP")
    lines.append("#define EQOPT_TESTS_GOLDEN_VECTORS_HPP")
    lines.append("")
    lines.append("#include <array>")
    lines.append("")
    lines.append('#include "eqopt/black_scholes.hpp"')
    lines.append("")
    lines.append("namespace eqopt::golden {")
    lines.append("")
    lines.append("/// One cross-language golden case: inputs plus the Python")
    lines.append("/// reference outputs (theta per year, vega per unit vol,")
    lines.append("/// rho per unit rate).")
    lines.append("struct GoldenCase {")
    lines.append("    double S, K, T, r, q, sigma;")
    lines.append("    eqopt::OptionType type;")
    lines.append("    double price, delta, gamma, vega, theta, rho;")
    lines.append("};")
    lines.append("")
    lines.append(
        f"inline constexpr std::array<GoldenCase, {len(cases)}> kCases"
        " = {{"
    )
    for c in cases:
        i = c["inputs"]
        o = c["outputs"]
        ot = ("eqopt::OptionType::Call" if i["type"] == "call"
              else "eqopt::OptionType::Put")
        lines.append("    {" + ", ".join([
            fmt(i["S"]), fmt(i["K"]), fmt(i["T"]), fmt(i["r"]),
            fmt(i["q"]), fmt(i["sigma"]), ot,
            fmt(o["price"]), fmt(o["delta"]), fmt(o["gamma"]),
            fmt(o["vega"]), fmt(o["theta"]), fmt(o["rho"]),
        ]) + "},")
    lines.append("}};")
    lines.append("")
    lines.append("}  // namespace eqopt::golden")
    lines.append("")
    lines.append("#endif  // EQOPT_TESTS_GOLDEN_VECTORS_HPP")
    lines.append("")

    header_path.write_text("\n".join(lines))
    print(f"Wrote {len(cases)} golden cases to {header_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
