#!/usr/bin/env python3
"""Generate src/golden.rs from the Python project's golden JSON.

The Python reference (python/fx/01-options-pricing) emits
tests/golden/golden_vectors.json; this script converts it into a Rust
module of static test vectors so the cargo test suite cross-validates the
Rust engine against the Python implementation with no runtime file I/O.

Usage:
    python3 tools/gen_golden_rs.py [json_path] [rs_path]

Defaults resolve relative to this repository layout.  Floats are emitted
with repr() (shortest round-trip representation), so the module reproduces
the JSON values bit-for-bit.
"""

from __future__ import annotations

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
DEFAULT_JSON = (HERE / ".." / ".." / ".." / "python" / "fx" /
                "01-options-pricing" / "tests" / "golden" /
                "golden_vectors.json").resolve()
DEFAULT_RS = (HERE / ".." / "src" / "golden.rs").resolve()

MODULE_TEMPLATE = """\
//! GENERATED FILE -- do not edit by hand.
//!
//! Produced by `tools/gen_golden_rs.py` from the Python reference
//! project's golden vectors:
//! `python/fx/01-options-pricing/tests/golden/golden_vectors.json`.
//!
//! {description}
//!
//! Source tolerance: {tolerance}; the Rust suite validates to 1e-9.

use crate::OptionType;

/// One golden validation case: pricing inputs plus the expected outputs
/// computed by the Python reference implementation (`fx_options`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GoldenCase {{
    /// Spot, domestic (quote) ccy per unit foreign (base) ccy.
    pub s: f64,
    /// Strike, same quotation as spot.
    pub k: f64,
    /// Time to expiry in years (ACT/365F).
    pub t: f64,
    /// Domestic (quote-ccy) continuously compounded rate.
    pub r_d: f64,
    /// Foreign (base-ccy) continuously compounded rate.
    pub r_f: f64,
    /// Annualised lognormal volatility.
    pub sigma: f64,
    /// Call or put on the base currency.
    pub option_type: OptionType,
    /// Expected premium, domestic ccy per unit foreign notional.
    pub price: f64,
    /// Expected unadjusted spot delta.
    pub delta_spot: f64,
    /// Expected unadjusted forward delta.
    pub delta_fwd: f64,
    /// Expected spot gamma.
    pub gamma: f64,
    /// Expected vega (per unit of vol).
    pub vega: f64,
    /// Expected theta (per year).
    pub theta: f64,
    /// Expected domestic rho.
    pub rho_d: f64,
    /// Expected foreign rho.
    pub rho_f: f64,
}}

/// The {n_cases} golden cases generated by the Python reference.
pub static CASES: [GoldenCase; {n_cases}] = [
{rows}
];
"""

ROW_TEMPLATE = """\
    GoldenCase {{
        s: {S},
        k: {K},
        t: {T},
        r_d: {r_d},
        r_f: {r_f},
        sigma: {sigma},
        option_type: {opt},
        price: {price},
        delta_spot: {delta_spot},
        delta_fwd: {delta_fwd},
        gamma: {gamma},
        vega: {vega},
        theta: {theta},
        rho_d: {rho_d},
        rho_f: {rho_f},
    }},"""


def fmt(x: float) -> str:
    """Shortest decimal that round-trips to the same double, as a valid
    Rust f64 literal (integral values keep a trailing `.0` from repr)."""
    text = repr(float(x))
    # repr() may produce forms like '1e-10' with no decimal point; Rust
    # accepts those as f64 literals, so no rewriting is needed.
    return text


def main() -> None:
    json_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_JSON
    rs_path = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_RS
    data = json.loads(json_path.read_text())
    cases = data["cases"]
    assert len(cases) == data["n_cases"], "case count mismatch in JSON"

    rows = []
    for case in cases:
        i, o = case["inputs"], case["outputs"]
        opt = ("OptionType::Call" if i["type"] == "call"
               else "OptionType::Put")
        rows.append(ROW_TEMPLATE.format(
            S=fmt(i["S"]), K=fmt(i["K"]), T=fmt(i["T"]),
            r_d=fmt(i["r_d"]), r_f=fmt(i["r_f"]), sigma=fmt(i["sigma"]),
            opt=opt,
            price=fmt(o["price"]), delta_spot=fmt(o["delta_spot"]),
            delta_fwd=fmt(o["delta_fwd"]), gamma=fmt(o["gamma"]),
            vega=fmt(o["vega"]), theta=fmt(o["theta"]),
            rho_d=fmt(o["rho_d"]), rho_f=fmt(o["rho_f"])))

    rs_path.write_text(MODULE_TEMPLATE.format(
        description=data.get("description", ""),
        tolerance=data.get("tolerance", ""),
        n_cases=len(cases),
        rows="\n".join(rows)))
    print(f"Wrote {rs_path} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
